name: example
description: A example app for qr_plus
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  qr_plus:
    path: ../

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.2

flutter:
  uses-material-design: true
