name: qr_plus
description: Advanced all-in-one qr code package with support for safe qr codes.
version: 1.3.0
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/qr_plus
issue_tracker: https://github.com/Mankeli-Software/qr_plus/issues
screenshots:
  - description: 'An example QR code rendered with QrPlusMode.paranoid'
    path: doc/asset/paranoid-qr.gif
  - description: 'An example QR code rendered with QrPlusMode.plain'
    path: doc/asset/plain-qr.jpg

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.5
  encrypt: 5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  mobile_scanner: ^6.0.2
  ntp: ^2.0.0
  qr_flutter: ^4.1.0
  screen_capture_event: ^1.1.1
  uuid: ^4.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mankeli_analysis: ^1.1.2
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.3

# package:derry scripts
scripts:
  gen:
    code: dart pub run build_runner build --delete-conflicting-outputs

false_secrets:
  - /lib/src/model/src/qr_plus_mode.dart
  - /lib/src/model/src/qr_plus_mode.g.dart
  - /lib/src/model/src/qr_plus_mode.gen.dart
